//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coditech.DataAccessLayer.DataEntity
{
    using System;

    public partial class AdminAssociateFormsToRole : CoditechEntityBaseModel
    {
        public int AdminAssociateFormsToRoleId { get; set; }
        public string AdminFormCode { get; set; }
        public byte AdminRoleMasterId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
