//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coditech.DataAccessLayer.DataEntity
{
    using System;

    public partial class ClientFile : CoditechEntityBaseModel
    {
        public long ClientFileId { get; set; }
        public int UserMasterId { get; set; }
        public string FileName { get; set; }
        public bool IsActive { get; set; }
        public bool FileStatus { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }

        public virtual UserMaster UserMaster { get; set; }
    }
}
