//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoditechBaseFramework.DataAccessLayer.DataEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RARIndiaEntities : DbContext
    {
        public RARIndiaEntities()
            : base("name=RARIndiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAssociateFormsToRole> AdminAssociateFormsToRoles { get; set; }
        public virtual DbSet<AdminRoleMaster> AdminRoleMasters { get; set; }
        public virtual DbSet<ClientFile> ClientFiles { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    }
}
