//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coditech.DataAccessLayer.DataEntity
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class CoditechEntities : DbContext
    {
        public CoditechEntities()
            : base("name=CoditechEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminAssociateFormsToRole> AdminAssociateFormsToRoles { get; set; }
        public virtual DbSet<AdminRoleMaster> AdminRoleMasters { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    }
}
