//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coditech.DataAccessLayer.DataEntity
{
    using System;

    public partial class ProductMaster : CoditechEntityBaseModel
    {
        public int ProductMasterId { get; set; }
        public string ProductName { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int DownloadCount { get; set; }
        public string ProductUniqueCode { get; set; }
        public string FileName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
